config/routes.rb
Rails.application.routes.draw do
  resources :charges
  resources :charges
  resources :users

end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :charge
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]

  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.includes(:user)
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create

    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url, notice: 'Charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:user_id,:price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/_form.html.slim
= form_for @charge, html: {class: "form-horizontal"} do |f|
  - if @charge.errors.any?
    #error_explanation
      h2 = "#{pluralize(@charge.errors.count, "error")} prohibited this charge from being saved:"
      ul
        - @charge.errors.full_messages.each do |message|
          li = message
  .form-group
      label.control-label.col-md-3 ユーザー
      .col-md-9
        = f.collection_select :user_id, User.all, :id, :user_name, class: "form-control"
  .form-group
      label.control-label.col-md-3 課金額(JPY)
      .col-md-9
        = f.text_field :price, class: "form-control"
  .form-group
      label.control-label.col-md-3 課金タイプ
      .col-md-9
        = f.select :type, [["通常ガチャ","1"],["10連ガチャ","2"],["薬10連ガチャ"]]
  .form-group
      label.control-label.col-md-3 課金時メッセージ
      .col-md-9
        = f.text_field :message
  .form-group
      label.control-label.col-md-3 ガチャ結果
      .col-md-9
        = f.text_field :response

  .text-center
    .actions = f.submit class: "btn btn-primary", value: "送信"

app/views/charges/edit.html.slim
h1 課金データの編集

== render 'form'

= link_to 'Show', @charge
'|
= link_to 'Back', charges_path

app/views/charges/index.html.slim
h1 課金情報

table.table.table-bordered
  thead
    tr
      th トランザクションID
      th 課金ユーザー
      th 課金額
      th 課金日時
      th 操作

    - @charges.each do |charge|
      tr
        td = sprintf("1%10d",charge.id)
        td = charge.user.user_name
        td
          = charge.price
          | JPY
        td = charge.created_at
        td
          .btn-group
            = link_to '詳細', charge, class: "btn btn-info "
            = link_to '課金補正', edit_charge_path(charge),  class: "btn btn-warning"
            = link_to '削除', charge, data: {:confirm => 'この課金データを本当に削除しますか？'}, :method => :delete,  class: "btn btn-danger"

br

= link_to '課金データを追加', new_charge_path, class: "btn btn-primary"

app/views/charges/new.html.slim
h1 課金データを追加

== render 'form'

= link_to 'Back', charges_path

app/views/charges/show.html.slim
p#notice = notice


= link_to 'Edit', edit_charge_path(@charge)
'|
= link_to 'Back', charges_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""
    title
      | 料金明細
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "料金明細", "/", class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li.active
              a href="/users"
                | ユーザー
            li
              a href="/charges"
                | 課金情報

    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Close
          = msg
      = yield

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} ユーザー情報の変更に失敗しました"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_name
    = f.text_field :user_name
  .field
    = f.label :user_id
    = f.text_field :user_id
  .actions = f.submit

app/views/users/edit.html.slim
h1 ユーザー編集

== render 'form'

= link_to '詳細', @user
'|
= link_to '戻る', users_path

app/views/users/index.html.slim
h1 ユーザー

table.table.table-bordered
  thead
    tr
      th ユーザーNo.
      th スクリーンネーム
      th 名前


  tbody
    - @users.each do |user|
      tr
        td = user.id
        td = user.user_name
        td = user.user_id
        td
          .btn-group
            = link_to '詳細', user, class: "btn btn-info "
            = link_to '課金補正', edit_user_path(user),  class: "btn btn-warning"
            = link_to '削除', user, data: {:confirm => '本当にユーザーを削除しますか？　ユーザーを削除しても、ガチャを回すと再び課金されます。'}, :method => :delete,  class: "btn btn-danger"




.text-right
  = link_to '新規追加', new_user_path, class: "btn btn-primary"

app/views/users/new.html.slim
h1 ユーザーの新規追加

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong ユーザー名（HN）
  = @user.user_name
p
  strong ユーザーのSlack ID
  = @user.user_id

= link_to '編集', edit_user_path(@user)
'|
= link_to '戻る', users_path